#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "~/.dotfiles/config/fish/completions/asdf.fish" "~/.config/fish/completions/asdf.fish"
handle_file_ln "~/.dotfiles/config/fish/completions/kubectl.fish" "~/.config/fish/completions/kubectl.fish"
handle_file_ln "~/.dotfiles/config/fish/completions/rustup.fish" "~/.config/fish/completions/rustup.fish"
handle_file_ln "~/.dotfiles/config/fish/conf.d/omf.fish" "~/.config/fish/conf.d/omf.fish"
handle_file_ln "~/.dotfiles/config/fish/config.fish" "~/.config/fish/config.fish"
handle_file_ln "~/.dotfiles/config/fish/fish-kubectl-completions/LICENSE" "~/.config/fish/fish-kubectl-completions/LICENSE"
handle_file_ln "~/.dotfiles/config/fish/fish-kubectl-completions/README.md" "~/.config/fish/fish-kubectl-completions/README.md"
handle_file_ln "~/.dotfiles/config/fish/fish-kubectl-completions/kubectl.fish" "~/.config/fish/fish-kubectl-completions/kubectl.fish"
handle_file_ln "~/.dotfiles/config/fish/fishd.186590cff659" "~/.config/fish/fishd.186590cff659"
handle_file_ln "~/.dotfiles/config/fish/functions/fish_prompt.fish" "~/.config/fish/functions/fish_prompt.fish"
handle_file_ln "~/.dotfiles/config/fish/functions/plugin-foreign-env/LICENSE" "~/.config/fish/functions/plugin-foreign-env/LICENSE"
handle_file_ln "~/.dotfiles/config/fish/functions/plugin-foreign-env/README.md" "~/.config/fish/functions/plugin-foreign-env/README.md"
handle_file_ln "~/.dotfiles/config/fish/functions/plugin-foreign-env/functions/fenv.apply.fish" "~/.config/fish/functions/plugin-foreign-env/functions/fenv.apply.fish"
handle_file_ln "~/.dotfiles/config/fish/functions/plugin-foreign-env/functions/fenv.fish" "~/.config/fish/functions/plugin-foreign-env/functions/fenv.fish"
handle_file_ln "~/.dotfiles/config/fish/functions/plugin-foreign-env/functions/fenv.main.fish" "~/.config/fish/functions/plugin-foreign-env/functions/fenv.main.fish"
handle_file_ln "~/.dotfiles/config/fish/functions/plugin-foreign-env/functions/fenv.parse.after.fish" "~/.config/fish/functions/plugin-foreign-env/functions/fenv.parse.after.fish"
handle_file_ln "~/.dotfiles/config/fish/functions/plugin-foreign-env/functions/fenv.parse.before.fish" "~/.config/fish/functions/plugin-foreign-env/functions/fenv.parse.before.fish"
handle_file_ln "~/.dotfiles/config/fish/functions/plugin-foreign-env/functions/fenv.parse.diff.fish" "~/.config/fish/functions/plugin-foreign-env/functions/fenv.parse.diff.fish"
handle_file_ln "~/.dotfiles/config/fish/functions/plugin-foreign-env/functions/fenv.parse.divider.fish" "~/.config/fish/functions/plugin-foreign-env/functions/fenv.parse.divider.fish"
handle_file_ln "~/.dotfiles/config/fish/functions/plugin-foreign-env/test.py" "~/.config/fish/functions/plugin-foreign-env/test.py"
handle_file_ln "~/.dotfiles/config/fish/functions/plugin-foreign-env/test.sh" "~/.config/fish/functions/plugin-foreign-env/test.sh"
handle_file_ln "~/.dotfiles/config/fish/functions/theme-sushi/LICENSE" "~/.config/fish/functions/theme-sushi/LICENSE"
handle_file_ln "~/.dotfiles/config/fish/functions/theme-sushi/README.md" "~/.config/fish/functions/theme-sushi/README.md"
handle_file_ln "~/.dotfiles/config/fish/functions/theme-sushi/fish_greeting.fish" "~/.config/fish/functions/theme-sushi/fish_greeting.fish"
handle_file_ln "~/.dotfiles/config/fish/functions/theme-sushi/fish_prompt.fish" "~/.config/fish/functions/theme-sushi/fish_prompt.fish"
handle_file_ln "~/.dotfiles/config/fish/functions/theme-sushi/fish_right_prompt.fish" "~/.config/fish/functions/theme-sushi/fish_right_prompt.fish"
handle_file_ln "~/.dotfiles/config/fish/functions/theme-sushi/fish_title.fish" "~/.config/fish/functions/theme-sushi/fish_title.fish"
handle_file_ln "~/.dotfiles/config/nvim/init.vim" "~/.config/nvim/init.vim"
handle_file_ln "~/.dotfiles/config/omf/bundle" "~/.config/omf/bundle"
handle_file_ln "~/.dotfiles/config/omf/channel" "~/.config/omf/channel"
handle_file_ln "~/.dotfiles/config/omf/theme" "~/.config/omf/theme"
handle_file_ln "~/.dotfiles/gitconfig" "~/.gitconfig"
handle_file_ln "~/.dotfiles/gitignore_global" "~/.gitignore_global"
handle_file_ln "~/.dotfiles/install.sh" "~/.install.sh"
handle_file_ln "~/.dotfiles/nix-profile/manifest.nix" "~/.nix-profile/manifest.nix"
